services:
  api:
    build:
      context: ./gsfcharman/
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - db:/var/lib/gsfcharman/chardata
    healthcheck:
      test: ["CMD", "httpx", "http://0.0.0.0:8000/debug"]
      interval: 1s
      retries: 1
      start_period: 5s
      timeout: 1s
    #restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./gsfcharman
          target: /opt/gsfcharman
          initial_sync: true
        - action: rebuild
          path: ./gsfcharman/requirements.txt
        - action: rebuild
          path: ./gsfcharman/api/Dockerfile

  xvfb:
    image: alpine
    #restart: unless-stopped
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:99
    init: true
    build:
      context: .
      dockerfile_inline: |
        FROM alpine:latest
        RUN apk add --no-cache xvfb
        ENTRYPOINT [ "Xvfb" ]
        CMD [ ":99", "-screen", "0", "1920x1200x16" ]

  daemon:
    build:
      context: ./gsfcharman/
      dockerfile: ./daemon/Dockerfile
      args:
        LICH_PATH: ${CONTAINER_LICH_PATH:-/opt/Lich5}
    ports:
      - "9000-9009:9000-9009"
    volumes:
      - type: bind
        source: ${LICH_PATH:-../lich}/data
        target: ${CONTAINER_LICH_PATH:-/opt/Lich5}/data
      - type: bind
        source: ${LICH_PATH:-../lich}/scripts
        target: ${CONTAINER_LICH_PATH:-/opt/Lich5}/scripts
      - type: bind
        source: ${LICH_PATH:-../lich}/logs
        target: ${CONTAINER_LICH_PATH:-/opt/Lich5}/logs
      - type: bind
        source: ${LICH_PATH:-../lich}/temp
        target: ${CONTAINER_LICH_PATH:-/opt/Lich5}/temp
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:99
    #restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
        restart: true
      xvfb:
        condition: service_started
    develop:
      watch:
        - action: sync+restart
          path: ./gsfcharman
          target: /opt/gsfcharman
          initial_sync: true
        - action: rebuild
          path: ./gsfcharman/requirements.txt
        - action: rebuild
          path: ./gsfcharman/daemon/Dockerfile

volumes:
  db:
