services:
  api:
    build:
      context: ./gsfcharman/
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - db:/var/lib/gsfcharman/chardata
    healthcheck:
      test: ["CMD", "httpx", "http://0.0.0.0:8000/debug"]
      interval: 1s
      retries: 1
      start_period: 5s
      timeout: 1s
    #restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./gsfcharman
          target: /opt/gsfcharman
          initial_sync: true
        - action: rebuild
          path: ./gsfcharman/requirements.txt
        - action: rebuild
          path: ./gsfcharman/api/Dockerfile
  daemon:
    build:
      context: ./gsfcharman/
      dockerfile: ./daemon/Dockerfile
    ports:
      - "9000-9010:9000-9010"
    volumes:
      - type: bind
        source: ../lich/data
        target: /opt/Lich5/data
      - type: bind
        source: ../lich/scripts
        target: /opt/Lich5/scripts
      - type: bind
        source: ../lich/logs
        target: /opt/Lich5/logs
    #restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: sync+restart
          path: ./gsfcharman
          target: /opt/gsfcharman
          initial_sync: true
        - action: rebuild
          path: ./gsfcharman/requirements.txt
        - action: rebuild
          path: ./gsfcharman/daemon/Dockerfile
    secrets:
      - entry_yaml

secrets:
  entry_yaml:
    file: ./entry.yaml

volumes:
  db:
