"""Async Login Orchestrator - Manages character login/logout decisions using strategies with async support."""

import subprocess
from typing import Dict, List, Optional

import httpx

from gsfcharman.api.data import CharacterData
from gsfcharman.daemon.config import API_URL, LICH_BIN, RUBY_BIN
from gsfcharman.daemon.strategies.base import LoginStrategy


class AsyncLoginOrchestrator:
    """Async orchestrator for character login decisions using layered strategies."""

    def __init__(
        self,
        strategies: List[LoginStrategy],
        characters: List[str],
        account: str,
        client: Optional[httpx.AsyncClient] = None,
        api_url: Optional[str] = API_URL,
        dryrun: bool = True,
    ):
        self.strategies = strategies
        self.characters = characters
        self.account = account
        self.dryrun = dryrun
        self.processes: Dict[str, subprocess.Popen] = {}
        self._owns_client = client is None

        # Handle client and API URL configuration
        if client is not None:
            # Use injected client - it should already be configured with base URL
            self.client = client
            self.api_url = None
        else:
            # Create default async client with API URL (use default if None)
            self.client = httpx.AsyncClient(base_url=api_url or API_URL)
            self.api_url = api_url or API_URL

    async def start_lich(self, character_name: str, port: int = 9000) -> subprocess.Popen:
        """Start a Lich process for a character."""
        cmd = [
            RUBY_BIN,
            LICH_BIN,
            "--login",
            character_name,
            "--shattered",
            "--detachable-client",
            str(port),
            "--without-frontend",
            "--start-scripts",
            "charman",
        ]
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        self.processes[character_name] = process
        return process

    def stop_lich(self, character_name: str) -> bool:
        """Stop a Lich process for a character."""
        process = self.processes.get(character_name)
        if process:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
            del self.processes[character_name]
            return True
        return False

    async def get_character_currently_logged_in(self) -> Optional[str]:
        """Get the character that is currently logged in.

        For each character we manage in this account, GET /characters/{name}/session and return
        the currently logged in character (is_logged_in is True).
        If more than one character is logged in, throw an exception.
        If no characters are logged in, return None.

        Returns:
            Name of the currently logged in character, or None if no characters are logged in

        Raises:
            RuntimeError: If more than one character is logged in
        """
        logged_in_characters = []

        # Use the client directly - it handles the base URL
        for char_name in self.characters:
            response = await self.client.get(f"/characters/{char_name}/session")
            if response.status_code == 200:
                session_data = response.json()
                if session_data.get("is_logged_in", False):
                    logged_in_characters.append(char_name)

        if len(logged_in_characters) > 1:
            raise RuntimeError(f"Multiple characters logged in: {logged_in_characters}")
        elif len(logged_in_characters) == 1:
            return logged_in_characters[0]
        else:
            return None

    async def get_character_selected_for_login(self) -> str:
        """Get the character that should be logged in based on strategies.

        For each character we manage in this account, GET /characters/{name} and evaluate
        our layered strategy with the list of character data.
        Returns the first character in the list generated by evaluating our strategies.
        If this list is empty, throw an exception.

        Returns:
            Name of the character that should be logged in

        Raises:
            RuntimeError: If no characters are selected by any strategy
        """
        # Fetch character data from API
        characters_data = []
        for char_name in self.characters:
            response = await self.client.get(f"/characters/{char_name}")
            if response.status_code == 200:
                char_data = CharacterData(**response.json())
                characters_data.append(char_data)

        # Apply layered strategies
        for strategy in self.strategies:
            selected_characters = strategy.select(characters_data)
            if selected_characters:
                # Return the first character from the first non-empty strategy result
                return selected_characters[0].name

        raise RuntimeError("No characters selected by any strategy")

    async def login_character(self) -> bool:
        """Handle the complete login workflow.

        Gets the currently logged in character, determines who should be logged in,
        and handles the transition if needed.

        Returns:
            True if a login action was performed, False if no action was needed
        """
        try:
            # Get current and target characters
            current_character = await self.get_character_currently_logged_in()
            target_character = await self.get_character_selected_for_login()

            # If different character should be logged in, handle the switch
            if current_character != target_character:
                if current_character:
                    if self.dryrun:
                        print(f"[DRYRUN] Account {self.account}: Would log out {current_character}...")
                    else:
                        print(f"Account {self.account}: Logging out {current_character}...")
                        self.stop_lich(current_character)

                if self.dryrun:
                    print(f"[DRYRUN] Account {self.account}: Would log in {target_character}...")
                else:
                    print(f"Account {self.account}: Logging in {target_character}...")
                    await self.start_lich(target_character)

                return True

            return False

        except Exception as e:
            print(f"Account {self.account}: Error in login workflow: {e}")
            return False

    async def close(self):
        """Close the HTTP client and clean up processes."""
        # Clean up any running processes
        for char_name, process in self.processes.items():
            print(f"Account {self.account}: Stopping Lich process for {char_name}...")
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()

        # Only close the client if we created it
        if self._owns_client:
            await self.client.aclose()

    async def __aenter__(self):
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit - close the client."""
        await self.close()
